{"attributes": {"fullName": "qx.core.AssertionError", "packageName": "qx.core", "type": "class", "name": "AssertionError", "superClass": "qx.type.BaseError"}, "type": "class", "children": [{"attributes": {"text": "<p>Assertion errors are thrown if an assertion in {@link qx.core.Assert}\nfails.</p>"}, "type": "desc"}, {"type": "constructor", "children": [{"attributes": {"overriddenFrom": "qx.type.BaseError", "isCtor": true, "name": "ctor"}, "type": "method", "children": [{"type": "params", "children": [{"attributes": {"name": "comment"}, "type": "param", "children": [{"attributes": {"text": "<p>Comment passed to the assertion call</p>"}, "type": "desc"}, {"type": "types", "children": [{"attributes": {"type": "String"}, "type": "entry"}]}]}, {"attributes": {"name": "failMessage"}, "type": "param", "children": [{"attributes": {"text": "<p>Fail message provided by the assertion</p>"}, "type": "desc"}, {"type": "types", "children": [{"attributes": {"type": "String"}, "type": "entry"}]}]}]}]}]}, {"type": "methods", "children": [{"attributes": {"name": "getStackTrace"}, "type": "method", "children": [{"attributes": {"text": "<p>Stack trace of the error</p>"}, "type": "desc"}, {"type": "return", "children": [{"attributes": {"text": "<p>The stack trace of the location the exception was thrown</p>"}, "type": "desc"}, {"type": "types", "children": [{"attributes": {"type": "String", "dimensions": 1}, "type": "entry"}]}]}]}]}]}